common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  
development:
  <<: *common
  database: codly_development

test:
  <<: *common
  database: codly_test

production:
  <<: *common
  database: codly_production
